### ISSUE TITLE
Get set up and get going with git !

### ISSUE THREAD

**Issue by TomBearpark** [TomBearpark/KIT_code_testing#1]
Hey @kitschwarz

First task - 

- [x] Make a new branch - call it something like "set_up"

- [x] Add a text file that says something hilarious ...

- [x] ... AND informative

- [x] Submit a pull request to me!

**Comment by kitschwarz** [comment]
https://github.com/TomBearpark/KIT_code_testing/pull/2

**Comment by kitschwarz** [comment]
jk https://github.com/TomBearpark/KIT_code_testing/pull/2/commits/8c9bcad358c810993c49225806cfdb311a540f69

**Comment by kitschwarz** [comment]
task completed and can now be merged into the master branch!

**Comment by TomBearpark** [comment]
excellent, thanks @kitschwarz . This is a great start, however, I just realized that I forgot to say that we should also have an interesting fact in that readme, as well as the hilarious joke you have already provided.

**Comment by TomBearpark** [comment]
could you edit the description of the issue, and then add a commit to  the Pull Request that addresses this concern?

**Comment by kitschwarz** [comment]
indeed i shall do so!

**Comment by kitschwarz** [comment]
new commit at https://github.com/TomBearpark/KIT_code_testing/pull/2/commits/8dfafdcd2de2499becd860f46538552d3c814127

**Comment by TomBearpark** [comment]
thanks @kitschwarz  - #2 closes this issue. 

I've deleted that branch. To stay up to date with this repo, checkout the master branch on your local machine, and then do a git pull. The master branch should now contain your changes
